name: BiggerThanChristmas
favicon: null
layout_spectrum: 0.77049
typography_spectrum: 0.5261383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.2597013
  lightness: 0.8887015
  saturation: 1
  rhythmicContrast: 0.7099494
purpose: []
